user_info_0: {bp: 3333, deviceName: test_name, port: 7777}
user_info_3: {bp: 3333, deviceName: test_name, port: 7777}
user_info_3: {bp: 3333, deviceName: test_name, port: 7777}
user_info_3: {bp: 3333, deviceName: test_name, port: 7777}
user_info_3: {bp: 3333, deviceName: test_name, port: 7777}
user_info_4: {bp: 4333, deviceName: test_name, port: 7777}
